function f_x = f(x)
% ======================================================================
% du = f(x)                                                             
%                                                                       
% システムの方程式の記述                                                
%                                                                       
% dot(x) = f(x) + g(x) * u                                              
%                                                                       
% システムの次元数分のxおよびpを与える。                                
% 与えられたシステムの方程式のうち、f(x)を入力する。                    
%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Nov-2020 11:06:05                                                                       
% ======================================================================


global  m l g J
q1 = x(1);
qdot1 = x(2);
f_x = [qdot1;(g.*l.*m.*sin(q1)-l.^2.*m.*qdot1.^2.*cos(q1).*sin(q1))./(J+l.^2.*m.*sin(q1).^2)];
