function HamG = HamG(x,p)
% ======================================================================
% du = HamF(x,p)                                                        
%                                                                       
% 正準方程式の非線形項の設定                                            
%                                                                       
% dot(x) =  ∂H/∂p                                                     
% dot(p) = -∂H/∂x                                                     
%                                                                       
% システムの次元数分のxおよびpを与える。                                
% 手計算またはMapleを用いて、g(x,p)を求め、その式を入力する。 
% それぞれ対角化されていない数式を入力する。
%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Nov-2020 11:06:15
% ======================================================================

global m l g J R

xp = [ x ;
    p ];

q1 = xp(1);
qdot1 = xp(2);
p1 = xp(3);
p2 = xp(4);
HamG = [-(p2.*(g.*l.*m.*cos(q1)-l.^2.*m.*qdot1.^2.*cos(q1).^2+l.^2.*m.*qdot1.^2.*sin(q1).^2))./(J+l.^2.*m.*sin(q1).^2)+(g.*l.*m.*p2)./J-(l.^2.*p2.^2.*cos(q1).*sin(q1).*1.0./(J+l.^2.*m.*sin(q1).^2).^2)./(R.*2.0)-(l.^4.*m.*p2.^2.*cos(q1).^3.*sin(q1).*1.0./(J+l.^2.*m.*sin(q1).^2).^3)./R+l.^2.*m.*p2.*cos(q1).*sin(q1).*(g.*l.*m.*sin(q1)-l.^2.*m.*qdot1.^2.*cos(q1).*sin(q1)).*1.0./(J+l.^2.*m.*sin(q1).^2).^2.*2.0;(l.^2.*m.*p2.*qdot1.*cos(q1).*sin(q1).*2.0)./(J+l.^2.*m.*sin(q1).^2)];
